{
 "title": "MQTT Monitor",
 "refresh": "10s",
 "panels": [
  {
   "title": "Pods Activos",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"cpu\" and exists r.topic and r.topic =~ /^pod\\//) |> distinct(column: \"topic\") |> group() |> count()"
    }
   ]
  },
  {
   "title": "Uso de CPU (pod entrenador-*)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\") |> range(start: -15m) |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"cpu\" and r.topic =~ /pod\\/entrenador-.*/) "
    }
   ]
  },
  {
   "title": "Uso de Memoria (pod entrenador-*)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\") |> range(start: -15m) |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"memoria\" and r.topic =~ /pod\\/entrenador-.*/) "
    }
   ]
  },
  {
   "title": "Uso de CPU (pod inferidor-*)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\") |> range(start: -15m) |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"cpu\" and r.topic =~ /pod\\/inferidor-.*/) "
    }
   ]
  },
  {
   "title": "Uso de Memoria (pod inferidor-*)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\") |> range(start: -15m) |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"memoria\" and r.topic =~ /pod\\/inferidor-.*/) "
    }
   ]
  },
  {
   "title": "Versión de actual del Modelo",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\") |> range(start: -30d) |> filter(fn: (r) => r._measurement == \"mqtt_consumer\" and r._field == \"cambios\" and r.topic == \"data/modelo\") |> last()"
    }
   ]
  },
  {
   "title": "Distribución (Train)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\") |> range(start: -30d) |> filter(fn: (r) => r._measurement == \"distribucion\" and (r._field == \"cantidad\" or r._field == \"proporcion\") and r.origen == \"train\") |> pivot( rowKey: [ \"inundado\", \"transitable\"], columnKey: [\"_field\"], valueColumn: \"_value\" ) |> group(columns: [\"inundado\", \"transitable\"]) |> keep(columns: [\"_time\", \"inundado\", \"transitable\", \"cantidad\", \"proporcion\"])"
    }
   ]
  },
  {
   "title": "Distribución (Test)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"my-bucket\") |> range(start: -30d) |> filter(fn: (r) => r._measurement == \"distribucion\" and (r._field == \"cantidad\" or r._field == \"proporcion\") and r.origen == \"test\") |> pivot( rowKey: [ \"inundado\", \"transitable\"], columnKey: [\"_field\"], valueColumn: \"_value\" ) |> group(columns: [\"inundado\", \"transitable\"]) |> keep(columns: [\"_time\", \"inundado\", \"transitable\", \"cantidad\", \"proporcion\"])"
    }
   ]
  }
 ]
}