apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-metrics-reader
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"] 
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pod-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-metrics-reader
subjects:
- kind: ServiceAccount
  name: metrics-reader
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-client
  template:
    metadata:
      labels:
        app: metrics-client
    spec:
      serviceAccountName: metrics-reader
      containers:
      - name: metrics-client
        image: bitnami/kubectl:latest
        command: 
        - "sh"
        - "-c"
        - |
          while true; do
            kubectl get --raw "/apis/metrics.k8s.io/v1beta1/pods" | jq '.items[] | {name: .metadata.name, cpu: .containers[].usage.cpu, memory: .containers[].usage.memory}';
            sleep 60;
          done
        